In [1]:


print('Hello World')

Hello World


In [2]:
import numpy as np


In [8]:
b = [1, 0, 0, 1]
a = np.array(b)
a = a.reshape(2,2)
print(a)

[[1 0]
 [0 1]]


In [11]:
d = dict()
d ={'Age': 20,
    'Height': 1.7,
    'Color': 'black',
    }
d['Age'] = 21
d['Height'] = 1.8
d['Color'] = 'white'
print(d)

{'Age': 21, 'Height': 1.8, 'Color': 'white'}


In [16]:
if 'Age' in d:
  print(d['Age'])

21


In [19]:
import matplotlib.pyplot as plt


In [1]:
x = [1, 2, 3, 4, 5, 8]
y = [2, 4, 6, 8, 10, 15]
xp = np.array(x)
yp = np.array(y)
plt.plot(xp, yp)
plt.show()

NameError: name 'np' is not defined

In [21]:
import pandas as pd


In [27]:
data = {'x': [1,2,3,4,5], 'y': [2,4,6,8,10]}
df = pd.DataFrame(data)
print(df)

   x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10


In [28]:
a = df.to_numpy()
print(a)

[[ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]]


In [29]:
a.reshape(2,5)
a.reshape(5,2)

array([[ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10]])